# Generated by Django 5.0.6 on 2024-06-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_virtualaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualaccount',
            name='account_name',
        ),
    ]
