# Generated by Django 5.0.6 on 2024-07-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_balance_development'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
